# Generated by Django 5.0.2 on 2024-03-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_sibi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sibi',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='massage',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='enquiryform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
